language: node_js
node_js:
  - "stable"
cache:
  bundler: true
  directories:
  - "$HOME/.npm"
  - "$HOME/.nvm"
  - "$HOME/.node"
  - "node_modules"
  - "client/node_modules"
before_install:
  # Install npm globally.
  - npm i -g npm
  # Install the server side node modules.
  - npm install
  - pwd
  # Install the client side node modules.
  - cd client && npm install
script:
  - pwd
  # Build the client side App.
  - npm run build
deploy:
  - provider: script
    script: ../deploy.sh master
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ../deploy.sh develop
    skip_cleanup: true
    on:
      branch: develop

# Only allow pushes to master to build with travis
branches:
  only:
    - master
    - develop
    - /^hotfix/.*$/
    - /^release/.*$/